### ISSUE TITLE
links include source path when base url is set

### ISSUE THREAD

**Issue by joshbeard** [joshbeard/web-indexer#21]
When running with `--base-url` specified

```shell
web-indexer --config /deploy/web-indexer.yml --base-url 'https://get.dev.foo.bar'
```

With a config like this:

```yaml
source: /mnt/repos
target: /mnt/repos
link_to_index: false
relative_links: true
title: get.dev.foo.bar - {relativePath}
recursive: true
minify: true
order: desc
```

The links have the source in them - e.g. `https://get.dev.foo.bar/mnt/repos/sub`
